# Generated by Django 2.2.10 on 2021-01-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(default='', upload_to='mememedia/'),
        ),
    ]
